"""Dated starter data for local demos.

This module is deliberately a seed snapshot, not a claim of live market data.
Replace it with a live provider before using reports for time-sensitive work.
"""

from .models import CandidateCompany, Evidence, RotationSignal


FIXTURE_AS_OF = "2026-06-01"


def evidence(title: str, url: str) -> Evidence:
    return Evidence(title=title, url=url, observed_at=FIXTURE_AS_OF)


ROTATION_SIGNALS = {
    "Industrials": RotationSignal(
        sector="Industrials",
        direction="neutral",
        rationale=(
            "Seed snapshot only: verify price breadth, relative strength, volume, "
            "and institutional flow before treating this as a live signal."
        ),
        as_of=FIXTURE_AS_OF,
    ),
    "Technology": RotationSignal(
        sector="Technology",
        direction="neutral",
        rationale="Seed snapshot only: live rotation adapter not configured.",
        as_of=FIXTURE_AS_OF,
    ),
    "Photonics": RotationSignal(
        sector="Photonics",
        direction="neutral",
        rationale="Seed snapshot only: verify relative strength and volume across LITE, COHR, CIEN, and AAOI.",
        as_of=FIXTURE_AS_OF,
    ),
    "Semiconductors": RotationSignal(
        sector="Semiconductors",
        direction="neutral",
        rationale="Seed snapshot only: verify rotation across memory, equipment, foundry, and chip-design names.",
        as_of=FIXTURE_AS_OF,
    ),
    "Systems": RotationSignal(
        sector="Systems",
        direction="neutral",
        rationale="Seed snapshot only: verify whether AI infrastructure spending is flowing into server vendors.",
        as_of=FIXTURE_AS_OF,
    ),
}


COMPANIES = (
    CandidateCompany(
        ticker="CAT",
        name="Caterpillar",
        sector="Industrials",
        industry="Construction Machinery",
        market_cap_b=220.0,
        value_chain_layer="obvious leader: heavy equipment",
        exposure="direct",
        thesis_keywords=("construction", "equipment", "infrastructure", "machinery"),
        summary="Global heavy-equipment leader and the obvious first-order beneficiary.",
        catalysts=("Infrastructure activity", "Dealer inventory normalization"),
        risks=("Cyclical demand slowdown", "Large-cap expectations already embedded"),
        invalidation_signals=("Construction backlog contracts", "Dealer inventories rise sharply"),
        evidence=(evidence("Caterpillar investor relations", "https://investors.caterpillar.com/"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="ASTE",
        name="Astec Industries",
        sector="Industrials",
        industry="Roadbuilding Equipment",
        market_cap_b=0.9,
        value_chain_layer="second-order: roadbuilding and asphalt equipment",
        exposure="direct",
        thesis_keywords=("asphalt", "construction", "equipment", "infrastructure", "roadbuilding"),
        summary="Roadbuilding-equipment manufacturer with exposure to asphalt plants, pavers, crushers, and infrastructure activity.",
        catalysts=("Road and bridge spending", "Equipment replacement cycle"),
        risks=("Small-cap cyclicality", "Input-cost pressure"),
        invalidation_signals=("Backlog declines materially", "Public-infrastructure activity weakens"),
        evidence=(
            evidence("Astec investor relations", "https://investors.astecindustries.com/"),
            evidence("Astec company overview", "https://www.astecindustries.com/"),
            evidence("Astec SEC filings", "https://www.sec.gov/edgar/browse/?CIK=792987"),
        ),
        liquidity="medium",
        risk_flags=("small cap",),
    ),
    CandidateCompany(
        ticker="MTW",
        name="The Manitowoc Company",
        sector="Industrials",
        industry="Cranes and Lifting Equipment",
        market_cap_b=0.5,
        value_chain_layer="second-order: cranes and lifting equipment",
        exposure="direct",
        thesis_keywords=("construction", "crane", "equipment", "infrastructure", "lifting"),
        summary="Crane manufacturer exposed to lifting demand from construction activity.",
        catalysts=("Non-residential construction activity", "Fleet replacement demand"),
        risks=("Highly cyclical end markets", "Low market capitalization"),
        invalidation_signals=("Orders and backlog decline", "Rental customers defer fleet renewal"),
        evidence=(
            evidence("Manitowoc investor relations", "https://ir.manitowoc.com/"),
            evidence("Manitowoc SEC filings", "https://www.sec.gov/edgar/browse/?CIK=61986"),
        ),
        liquidity="medium",
        risk_flags=("small cap", "cyclical"),
    ),
    CandidateCompany(
        ticker="HEES",
        name="H&E Equipment Services",
        sector="Industrials",
        industry="Equipment Rental",
        market_cap_b=2.0,
        value_chain_layer="second-order: equipment rental",
        exposure="indirect",
        thesis_keywords=("construction", "equipment", "infrastructure", "rental"),
        summary="Equipment-rental operator that can benefit when contractors rent rather than purchase machinery for expanding project pipelines.",
        catalysts=("Rental utilization", "Construction project growth"),
        risks=("Fleet financing costs", "Utilization decline"),
        invalidation_signals=("Rental rates weaken", "Fleet utilization declines"),
        evidence=(
            evidence("H&E investor relations", "https://investor.he-equipment.com/"),
            evidence("H&E SEC filings", "https://www.sec.gov/edgar/browse/?CIK=1339605"),
        ),
        liquidity="medium",
        risk_flags=("leverage sensitivity",),
    ),
    CandidateCompany(
        ticker="URI",
        name="United Rentals",
        sector="Industrials",
        industry="Equipment Rental",
        market_cap_b=45.0,
        value_chain_layer="established leader: equipment rental",
        exposure="indirect",
        thesis_keywords=("construction", "equipment", "infrastructure", "rental"),
        summary="Large equipment-rental operator with broad construction exposure.",
        catalysts=("Rental utilization", "Infrastructure activity"),
        risks=("Large-cap expectations", "Cyclical utilization"),
        invalidation_signals=("Rental rates decline", "Fleet utilization weakens"),
        evidence=(evidence("United Rentals investor relations", "https://investor-relations.unitedrentals.com/"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="GVA",
        name="Granite Construction",
        sector="Industrials",
        industry="Infrastructure Construction",
        market_cap_b=4.0,
        value_chain_layer="adjacent: infrastructure contractor",
        exposure="indirect",
        thesis_keywords=("construction", "infrastructure", "roadbuilding"),
        summary="Infrastructure contractor with exposure to public works activity.",
        catalysts=("Public works awards", "Infrastructure backlog"),
        risks=("Project execution", "Margin pressure"),
        invalidation_signals=("Award activity declines", "Margins deteriorate"),
        evidence=(evidence("Granite investor relations", "https://investor.graniteconstruction.com/"),),
        liquidity="medium",
        risk_flags=("project execution",),
    ),
    CandidateCompany(
        ticker="LITE",
        name="Lumentum",
        sector="Photonics",
        industry="Optical Components",
        market_cap_b=25.0,
        value_chain_layer="L8 connectivity: optical components",
        exposure="direct",
        thesis_keywords=("ai", "data", "center", "optical", "networking", "photonics", "bottleneck"),
        summary="Optical-component supplier exposed to AI data-center connectivity demand.",
        catalysts=("AI optical-interconnect demand", "Capacity expansion"),
        risks=("Valuation compression", "Customer concentration"),
        invalidation_signals=("Optical demand guidance weakens", "Capacity expansion outpaces demand"),
        evidence=(evidence("Lumentum investor relations", "https://investor.lumentum.com/"),),
        liquidity="high",
        risk_flags=("customer concentration",),
    ),
    CandidateCompany(
        ticker="COHR",
        name="Coherent",
        sector="Photonics",
        industry="Optical Components",
        market_cap_b=20.0,
        value_chain_layer="L8 connectivity: optical components",
        exposure="direct",
        thesis_keywords=("ai", "data", "center", "optical", "networking", "photonics", "bottleneck"),
        summary="Optical and photonics supplier with AI data-center connectivity exposure.",
        catalysts=("Datacom demand", "Optical capacity utilization"),
        risks=("Execution complexity", "Cyclical demand"),
        invalidation_signals=("Datacom growth decelerates", "Margins weaken materially"),
        evidence=(evidence("Coherent investor relations", "https://investors.coherent.com/"),),
        liquidity="high",
        risk_flags=("execution complexity",),
    ),
    CandidateCompany(
        ticker="CIEN",
        name="Ciena",
        sector="Photonics",
        industry="Optical Networking",
        market_cap_b=15.0,
        value_chain_layer="L8 connectivity: optical networking systems",
        exposure="direct",
        thesis_keywords=("ai", "data", "center", "optical", "networking", "photonics", "bottleneck"),
        summary="Networking vendor exposed to bandwidth demand and optical transport upgrades.",
        catalysts=("Network capacity upgrades", "Cloud-provider spending"),
        risks=("Carrier spending variability", "Competitive pressure"),
        invalidation_signals=("Orders weaken", "Cloud-provider spending slows"),
        evidence=(evidence("Ciena investor relations", "https://investor.ciena.com/"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="CRDO",
        name="Credo Technology",
        sector="Photonics",
        industry="High-Speed Connectivity",
        market_cap_b=20.0,
        value_chain_layer="L8 connectivity: high-speed data links",
        exposure="direct",
        thesis_keywords=("ai", "data", "center", "connectivity", "networking", "optical", "bottleneck"),
        summary="Connectivity supplier exposed to high-speed links inside AI infrastructure.",
        catalysts=("AI cluster scaling", "High-speed connectivity adoption"),
        risks=("High expectations", "Customer concentration"),
        invalidation_signals=("Design-win momentum slows", "Customer concentration worsens"),
        evidence=(evidence("Credo investor relations", "https://investors.credosemi.com/"),),
        liquidity="high",
        risk_flags=("customer concentration",),
    ),
    CandidateCompany(
        ticker="MU",
        name="Micron Technology",
        sector="Semiconductors",
        industry="Memory",
        market_cap_b=500.0,
        value_chain_layer="L6 memory: HBM and bandwidth",
        exposure="direct",
        thesis_keywords=("ai", "memory", "bandwidth", "hbm", "bottleneck", "semiconductor"),
        summary="Memory supplier exposed to AI demand for bandwidth-intensive HBM products.",
        catalysts=("HBM demand", "Memory pricing"),
        risks=("Memory cyclicality", "Competitive supply"),
        invalidation_signals=("HBM demand weakens", "Memory pricing rolls over"),
        evidence=(evidence("Micron investor relations", "https://investors.micron.com/"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="SNDK",
        name="SanDisk",
        sector="Semiconductors",
        industry="Memory and Storage",
        market_cap_b=40.0,
        value_chain_layer="L6 memory: storage adjacency",
        exposure="indirect",
        thesis_keywords=("ai", "memory", "storage", "bandwidth", "bottleneck", "semiconductor"),
        summary="Memory and storage adjacency for research when capital rotates through the memory layer.",
        catalysts=("Memory-sector rotation", "Storage demand"),
        risks=("Cyclical pricing", "Indirect HBM exposure"),
        invalidation_signals=("Memory-sector breadth weakens", "Storage pricing deteriorates"),
        evidence=(evidence("SanDisk investor relations", "https://investor.sandisk.com/"),),
        liquidity="high",
        risk_flags=("indirect exposure",),
    ),
    CandidateCompany(
        ticker="ASML",
        name="ASML",
        sector="Semiconductors",
        industry="Semiconductor Equipment",
        market_cap_b=550.0,
        value_chain_layer="L4 equipment: lithography",
        exposure="direct",
        thesis_keywords=("ai", "semiconductor", "equipment", "euv", "foundry", "bottleneck"),
        summary="Semiconductor-equipment supplier positioned at a critical lithography bottleneck.",
        catalysts=("Foundry capex", "Advanced-node demand"),
        risks=("Export controls", "Capex-cycle delays"),
        invalidation_signals=("Foundry capex weakens", "Order backlog declines materially"),
        evidence=(evidence("ASML investor relations", "https://www.asml.com/en/investors"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="TSM",
        name="Taiwan Semiconductor Manufacturing",
        sector="Semiconductors",
        industry="Foundry",
        market_cap_b=1400.0,
        value_chain_layer="L3 foundry: advanced fabrication",
        exposure="direct",
        thesis_keywords=("ai", "semiconductor", "foundry", "fabrication", "bottleneck"),
        summary="Advanced foundry leader downstream of equipment and upstream of AI chip designers.",
        catalysts=("Advanced-node demand", "AI accelerator demand"),
        risks=("Geopolitical risk", "Capex intensity"),
        invalidation_signals=("Advanced-node utilization falls", "AI accelerator forecasts weaken"),
        evidence=(evidence("TSMC investor relations", "https://investor.tsmc.com/english"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="NVDA",
        name="NVIDIA",
        sector="Semiconductors",
        industry="Chip Design",
        market_cap_b=4500.0,
        value_chain_layer="L2 chip design: AI accelerators",
        exposure="direct",
        thesis_keywords=("ai", "semiconductor", "chip", "design", "accelerator"),
        summary="AI-accelerator leader and a demand source for downstream bottleneck analysis.",
        catalysts=("Hyperscaler capex", "Accelerator demand"),
        risks=("Valuation expectations", "Competition"),
        invalidation_signals=("Hyperscaler capex slows", "Accelerator growth decelerates"),
        evidence=(evidence("NVIDIA investor relations", "https://investor.nvidia.com/"),),
        liquidity="high",
    ),
    CandidateCompany(
        ticker="SMCI",
        name="Super Micro Computer",
        sector="Systems",
        industry="AI Server Systems",
        market_cap_b=30.0,
        value_chain_layer="L9 systems: AI servers",
        exposure="direct",
        thesis_keywords=("ai", "data", "center", "server", "system", "infrastructure"),
        summary="Server-systems vendor exposed to AI infrastructure deployment.",
        catalysts=("AI server demand", "Rack-scale deployment"),
        risks=("Execution risk", "Competitive pressure"),
        invalidation_signals=("Server demand weakens", "Margins deteriorate"),
        evidence=(evidence("Supermicro investor relations", "https://ir.supermicro.com/"),),
        liquidity="high",
        risk_flags=("execution risk",),
    ),
)
